### ISSUE TITLE
Bamboo unable to detect the Ruby installation on a Windows PC after installing the plugin

### ISSUE THREAD

**Issue by daniel-d** [wolfeidau/rake-bamboo-plugin#28]
I've installed this plugin but afterwards Bamboo doesn't  auto detect ruby installations on Windows (XP) based servers.

I’ve installed Ruby using both the standalone RubyInstall for Windows and RailsInstaller, but in both instances after installing the Bamboo Ruby Plugin (v1.8 & v1.10) the “Detect Server Capabilities” button cannot determine where the ruby executable is installed (the system %path% was updated, and the server rebooted, Bamboo version is 4.1 Windows Installer 32-bit).

Is there a way to manually add a Ruby Environment server capability that this plugin can then use?

Let me know if any further information RE my system config is required.

**Comment by pcsgithubid** [comment]
in the linux environment both jruby and ruby are installed ,but bamboo is able detect only ruby,and our project uses jruby .how to fix this issue.bamboo-ruby plugin os insatlled in bamboo and we are using this for bundle and rake.
