### ISSUE TITLE
Plugin does not work Bamboo version 5.7.x

### ISSUE THREAD

**Issue by olisun** [wolfeidau/rake-bamboo-plugin#86]
We are planning to use this plugin with our instance of Bamboo but it doesn't seem to be working.

The Ruby runtime drop down select list is not available and throws the following exception when I try to configure the task.

2014-12-05 13:34:47,039 INFO [http-bio-8080-exec-17] [AccessLogFilter] oliver.pereira POST https://testbamboo.gamesys.corp/build/admin/edit/createTask.action 634096kb
2014-12-05 13:34:47,051 ERROR [http-bio-8080-exec-17] [runtime] Expression invalidRuntime is undefined on line 4, column 6 in bundler/install/editBundlerInstallTask.ftl.

Expression invalidRuntime is undefined on line 4, column 6 in bundler/install/editBundlerInstallTask.ftl.
The problematic instruction:
----------
==> if-else  [on line 4, column 1 in bundler/install/editBundlerInstallTask.ftl]
----------

Java backtrace for programmers:
----------
freemarker.core.InvalidReferenceException: Expression invalidRuntime is undefined on line 4, column 6 in bundler/install/editBundlerInstallTask.ftl.
        at freemarker.core.TemplateObject.assertNonNull(TemplateObject.java:124)

**Comment by n1tr0g** [comment]
:+1:

**Comment by swistaczek** [comment]
Hey, same issue with NullPointerException occuring on  5.6.2 build 4411.

**Comment by wolfeidau** [comment]
Heya, at the moment I don't use bamboo so hence me not being very responsive with upgrades.

Has anyone diagnosed the issue? I would love a pull request for this.

**Comment by felder** [comment]
Bamboo 5.6.3 also indicates that the plugin is incompatible.

**Comment by jrdaniels** [comment]
I would be happy with the recompile that @olisun did, as I'm not using any remote agents.  

Also, @wolfeidau have you moved on to a different CI server platform for your projects?

**Comment by wolfeidau** [comment]
Yeah I use https://buildkite.com/ now, fantastic service and way simpler to operate.

Just a note I am closing this issue as i am not maintaining this plugin anymore.

**Comment by dgolja** [comment]
buildkite looks nice ! tnx for all your hard work in the past. Hopefully bamboo will finally ship an official support for ruby.

**Comment by wolfeidau** [comment]
Thanks much appreciated, I will also mention it on twitter to nudge them :)

**Comment by OliverPereira** [comment]
@n1tr0g - I doubt Atlassian is going to bother about it.

**Comment by dgolja** [comment]
Probably true, but sadly as far as I know they don't support ruby testing by default. I had to build a custom elastic client and define the capabilities/commands manually.

https://confluence.atlassian.com/display/BAMBOO/Getting+started+with+Ruby+and+Bamboo
https://jira.atlassian.com/browse/BAM-10948
